18 support multiple nrf cloud accounts
hello-nrfcloud/backend pull request #116
Opened 2023-07-17 12:31 UTC by pudkrong

2023-07-17 14:19 UTC, coderbyheart commented on cdk/resources/containers/bridge/mosquitto.bridge.conf
Only comments?

2023-07-24 07:48 UTC, coderbyheart commented on cli/commands/migrate-nrfcloud-account.ts
We don't need to preserve one-time operations in code as long as we don't test that they work now and in the future. 

I don't want to have to maintain code that we will never use in the future.

It's sufficient to attach the migration instructions to the release notes.

2023-07-25 15:40 UTC, pudkrong commented
- Delete migration section from README.md
- Will delete migration cli after PR is approved
- FingerPrint of health check device will be suffix with account name i.e. 29a.ch3ckr.exeger

2023-07-25 16:13 UTC, pudkrong commented on cli/commands/migrate-nrfcloud-account.ts
I will keep this cli for now until PR is approved.

2023-07-26 06:36 UTC, coderbyheart requested changes
- make accounts dynamic
- add CLI to list accounts
- do not use brand names for test data

2023-07-26 06:36 UTC, coderbyheart commented on .github/workflows/test-and-release.yaml
> +          ./cli.sh fake-nrfcloud-account-device exeger
Use fantasy names for testing, e.g. "ACME"

2023-07-26 06:36 UTC, coderbyheart commented on README.md
> +**Note** Currently the supported accounts are `exeger` and `nordic`
Should not be hard-coded. Adding or removing account should not involve source code changes.

2023-07-26 06:36 UTC, coderbyheart commented on cli/cli.ts
> +					console.log('error>>>>', error)
Remove.

2023-07-26 06:36 UTC, coderbyheart commented on cli/cli.ts
> +				migrateNRFCloudAccounts({
Remove.

2023-07-26 06:36 UTC, coderbyheart commented on cli/commands/configure-device.ts
> +	command: 'configure-device <account> <fingerprint>',
This should not be neccessary. We know the association between a device and an account. Fingerprints are globally unique.

2023-07-26 06:36 UTC, coderbyheart commented on cli/commands/configure.ts
> +const validScopes = [Scope.EXEGER_CONFIG, Scope.NODIC_CONFIG]
Fetch available scopes dynamically.

2023-07-26 06:36 UTC, coderbyheart commented on feature-runner/steps/device.ts
> +			/^I have the fingerprint under `(?<account>[^`]+)` account for a `(?<model>[^`]+)` device in `(?<storageName>[^`]+)`$/,
```suggestion
			/^I have the fingerprint for a `(?<model>[^`]+)` device(?<maybeAccount> in the `(?<account>[^`]+)` account) in `(?<storageName>[^`]+)`$/,
```

Make the account optional, and use the default if not needed during a test.

2023-07-26 06:36 UTC, coderbyheart commented on feature-runner/steps/mocknRFCloud.ts
> +			/^there is a device shadow request for `(?<deviceId>[^`]+)` with API key of `(?<account>[^`]+)` account$/,
```suggestion
			/^the shadow for `(?<deviceId>[^`]+)` in the `(?<account>[^`]+)` account has been requested$/,
```

2023-07-26 06:36 UTC, coderbyheart commented on features/MultipleNRFCloudAccounts.feature.md
> +## Verify a nodic device sends shadow data to nRF Cloud, then there is shadow request with associated api key
```suggestion
## Verify a Nordic device sends shadow data to nRF Cloud, then there is a shadow request with associated API key
```

2023-07-26 06:36 UTC, coderbyheart commented on features/MultipleNRFCloudAccounts.feature.md
> +## Verify a exeger device sends shadow data to nRF Cloud, then there is shadow request with associated api key
```suggestion
## Verify a ACME device sends shadow data to nRF Cloud and there is a shadow request with the associated API key
```

2023-07-26 06:36 UTC, coderbyheart commented on features/DeviceInfo.feature.md
> +Given I have the fingerprint under `exeger` account for a `PCA20035+solar`
```suggestion
Given I have the fingerprint under `ACME` account for a `PCA20035+solar`
```

2023-07-26 06:36 UTC, coderbyheart commented on nrfcloud/allAccounts.ts
> +] as const
Use dynamic list.

2023-07-27 13:07 UTC, coderbyheart requested changes

2023-07-27 13:07 UTC, coderbyheart commented on README.md
> +You can create a simulated device for particular nRF Cloud account using the
```suggestion
You can create a simulated device for a particular nRF Cloud account using the
```

2023-07-27 13:07 UTC, coderbyheart commented on cdk/backend.ts
> +)
`getAllAccountsSettings` should be trusted. No need to double check here.

 ` nRFCloudAccounts` should be a `Record<string, ...>` because there can (and should) only be one account with each key, while the current structure does not enforce this.

Use result of `getAllAccountsSettings` directly.

2023-07-27 13:07 UTC, coderbyheart commented on cdk/resources/ConfigureDevice.ts
> +						}:parameter/${Stack.of(this).stackName}/thirdParty/${account}/*`,
Simplify this by using wildcard.
```suggestion
						}:parameter/${Stack.of(this).stackName}/thirdParty/*`,
```

2023-07-27 13:07 UTC, coderbyheart commented on cdk/resources/DeviceShadow.ts
> +						}:parameter/${Stack.of(this).stackName}/thirdParty/${account}/*`,
Simplify this by using wildcard.

```suggestion
						}:parameter/${Stack.of(this).stackName}/thirdParty/*`,
```

2023-07-27 13:07 UTC, coderbyheart commented on cdk/resources/HealthCheckMqttBridge.ts
> +						}:parameter/${Stack.of(this).stackName}/thirdParty/${account}`,
Simplify this by using wildcard.

```suggestion
						}:parameter/${Stack.of(this).stackName}/thirdParty/*`,
```

2023-07-27 13:07 UTC, coderbyheart commented on cli/commands/create-health-check-device.ts
> +			healthCheckFingerPrint: `29a.ch3ckr.${account}`,
This is not a valid fingerprint. Generate one.

2023-07-27 13:07 UTC, coderbyheart commented on cli/commands/list-nrfcloud-accounts.ts
> +	help: 'List all nRF Cloud accounts',
```suggestion
	help: 'List configured nRF Cloud accounts',
```

2023-07-27 13:07 UTC, coderbyheart commented on cli/commands/list-nrfcloud-accounts.ts
> +		const accountRows = accounts.map((account) => [chalk.green(account)])
Do not print API Keys fully. See cli/commands/show-nrfcloud-account.ts

2023-07-27 13:07 UTC, coderbyheart commented on migration/commands/migrate-nrfcloud-account.ts
Remove

2023-07-27 13:07 UTC, coderbyheart commented on migration/cli.ts
Remove

2023-07-27 13:07 UTC, coderbyheart commented on feature-runner/steps/device.ts
> +			/^I have the fingerprint under `(?<account>[^`]+)` account for a `(?<model>[^`]+)` in `(?<storageName>[^`]+)`$/,
```suggestion
			/^I have the fingerprint under `(?<account>[^`]+)` account for a `(?<model>[^`]+)` in `(?<storageName>[^`]+)`$/,
			/^I have the fingerprint for a `(?<model>[^`]+)` device(?<maybeAccount> in the `(?<account>[^`]+)` account) in `(?<storageName>[^`]+)`$/,
```

No need to change the other tests, use the default account.

2023-07-27 13:07 UTC, coderbyheart commented on nrfcloud/settings.ts
> +	scope: string
```suggestion
	account: string
```

So in the rest of the codebase you can get rid of this:

```typescript
const scope = `thirdParty/${account}`
```

2023-07-27 15:52 UTC, pudkrong commented on cli/commands/list-nrfcloud-accounts.ts
> +		const accountRows = accounts.map((account) => [chalk.green(account)])
I don't print API key, just account name.

2023-07-28 09:53 UTC, coderbyheart approved these changes
Thanks!

2023-07-28 21:29 UTC, merged

2023-07-29 07:30 UTC, coderbyheart commented
@pudkrong you merged this PR without following the commit style, which resulted in the merge not releasing a new major release. In the future please squash PRs into on (or few commits), following the commit message guides before merging them so we get a nice release history.

This is also a BREAKING CHANGE, please provide the migration instructions in the description of the release at https://github.com/hello-nrfcloud/backend/releases/tag/v4.0.0

2023-07-29 07:31 UTC, coderbyheart commented
I've now corrected this mistake and force-pushed a squash commit in https://github.com/hello-nrfcloud/backend/commit/adcc67ae03f6566758cc89786956eb2ab6682278