Fix coap measurement
hello-nrfcloud/backend pull request #381
Opened 2023-11-14 21:03 UTC by pudkrong

We are using a message timestamp to calculate the duration which is not accurate in case of CoAP because of calling CoAP simulator via `child_process` will take times to spawn the child process which we need to take into the account when calculation. 

So, we will use a timestamp from CoAP simulator log instead. The timestamp we use is the first timestamp when CoAP simulator establishes the connection the same way as we do on MQTT measurement.

2023-11-14 21:05 UTC, pudkrong commented
This is the graph comparing MQTT and CoAP after changes

<img width="1273" alt="image" src="https://github.com/hello-nrfcloud/backend/assets/2525169/38bf6487-1f77-4ad4-a93d-3cde92945f8f">

2023-11-15 09:06 UTC, coderbyheart requested changes

2023-11-15 09:06 UTC, coderbyheart commented on lambda/healthCheckForCoAP.ts
> +			)
Complicated parsing logic is easy to have mistakes, please add a test.

2023-11-15 09:06 UTC, coderbyheart commented on lambda/healthCheckForCoAP.ts
> +								(Date.now() - (data?.coapTs ?? data?.ts ?? 0)) / 1000,
This could report `receivingMessageDuration` as `Date.now()` which is wrong.

2023-11-15 12:39 UTC, coderbyheart approved these changes

2023-11-15 13:39 UTC, merged